name: Green DevOps Pipeline

on:
  push:
    paths:
      - "app.py"
      - "test_app.py"

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ runner.os }}

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest